### ISSUE TITLE
some typos in README

### ISSUE THREAD

**Issue by DavidBruchmann** [Beronimus/Typo3-CKEditor5-Plugin-Converter#1]
> This project is at the moment just a strating point
=> This project is at the moment just a starting point

> Change the entry point of the webpack.config.js to ponit to the entry of the plugin.
=> Change the entry point of the webpack.config.js to point to the entry of the plugin.

**Comment by Beronimus** [comment]
I fixed the mentioned typos.
Thank you for your help.
