### ISSUE TITLE
How to add another plugin?

### ISSUE THREAD

**Issue by tklmn** [Beronimus/Typo3-CKEditor5-Plugin-Converter#2]
If i change my webpack to build the code-block plugin like this:

    entry: './node_modules/@ckeditor/ckeditor5-code-block/src/codeblock.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'cke-code-block-plugin.js',
        library: {
            type: 'module',
        },
    },

after i execute 

    npm i @ckeditor/ckeditor5-code-block@38.1.0

i'll get this message with ```npm run build```

    WARNING in ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockcommand.js 64:27-32
    export 'first' (imported as 'first') was not found in 'ckeditor5/src/utils' (possible exports: CKEditorError, Collection, FocusTracker, KeystrokeHandler, ObservableMixin)
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockediting.js 11:0-50 72:45-61
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblock.js 9:0-50 25:16-32
    
    WARNING in ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockcommand.js 79:27-32
    export 'first' (imported as 'first') was not found in 'ckeditor5/src/utils' (possible exports: CKEditorError, Collection, FocusTracker, KeystrokeHandler, ObservableMixin)
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockediting.js 11:0-50 72:45-61
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblock.js 9:0-50 25:16-32
    
    WARNING in ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockediting.js 132:31-43
    export 'UpcastWriter' (imported as 'UpcastWriter') was not found in 'ckeditor5/src/engine' (possible exports: addBackgroundRules, isLength, isPercentage)
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblock.js 9:0-50 25:16-32
    
    WARNING in ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockui.js 36:56-71
    export 'SplitButtonView' (imported as 'SplitButtonView') was not found in 'ckeditor5/src/ui' (possible exports: ButtonView, ColorGridView, ColorPickerView, ColorTileView, FocusCycler, LabelView, Model, Template, View, ViewCollection, addListToDropdown, createDropdown, focusChildOnDropdownOpen, getLocalizedColorOptions, icons, normalizeColorOptions)
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblock.js 10:0-40 25:34-45
    
    WARNING in ./node_modules/@ckeditor/ckeditor5-code-block/src/utils.js 194:23-28
    export 'first' (imported as 'first') was not found in 'ckeditor5/src/utils' (possible exports: CKEditorError, Collection, FocusTracker, KeystrokeHandler, ObservableMixin)
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblockediting.js 14:0-132 70:40-84 134:27-63 227:29-50
     @ ./node_modules/@ckeditor/ckeditor5-code-block/src/codeblock.js 9:0-50 25:16-32

When i add ```export const first = Utils.first``` inside the ```cke-translator-utils.js```
and the rest in the other files i can build the package without an error. After that i'll get this in TYPO3 and the editor won't load.

    Uncaught (in promise) CKEditorError: ckeditor-duplicated-modules
    Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
        at cke-code-block-plugin.js?bust=5efc4e531294f9910d2d901eea9eb07ee9e3c8aa:2:13691
        at cke-code-block-plugin.js?bust=5efc4e531294f9910d2d901eea9eb07ee9e3c8aa:2:181280

**Comment by fiedomedia** [comment]
@tklmn same for me. Did you manage to fix that for Code-Block plugin?

**Comment by Beronimus** [comment]
I updated the project to convert the code-block plugin.

I did the same you did in your first step.
But this plugin uses additional classes, which have to be translated by the converter (ckeditor5/src/enter)
because they are already included in the typo3 installation.
